# Generated by Django 4.1.1 on 2022-09-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_account_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account',
            field=models.CharField(default='', max_length=20, verbose_name='Bank Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='addr1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='addr2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.CharField(default='', max_length=120, verbose_name='Bank Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='bk_currency',
            field=models.CharField(default='CAD', max_length=3, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnesst_rate',
            field=models.FloatField(default=0, verbose_name='CNESST Rate: W'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Canada', max_length=20, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(default='Quebec', max_length=20, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='qhsf_rate',
            field=models.FloatField(default=0, verbose_name='QHSF Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='company',
            name='wcb_rate',
            field=models.FloatField(default=0, verbose_name='WCB/WSIB Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip/Post Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to='manage.company'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User Name'),
        ),
    ]
