# Generated by Django 4.1.1 on 2022-09-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_company_account_company_addr1_company_addr2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bk_currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD'), ('CNY', 'CNY')], max_length=3, verbose_name='Currency'),
        ),
    ]
