# Generated by Django 4.1.1 on 2022-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_alter_company_bk_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank',
            field=models.CharField(blank=True, max_length=120, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bk_currency',
            field=models.CharField(blank=True, choices=[('CAD', 'CAD'), ('USD', 'USD'), ('CNY', 'CNY')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnesst_rate',
            field=models.FloatField(blank=True, verbose_name='CNESST Rate: W'),
        ),
        migrations.AlterField(
            model_name='company',
            name='qhsf_rate',
            field=models.FloatField(blank=True, verbose_name='QHSF Rate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wcb_rate',
            field=models.FloatField(blank=True, verbose_name='WCB/WSIB Rate'),
        ),
    ]
