# Generated by Django 4.1.1 on 2022-09-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0006_alter_company_cnesst_rate_alter_company_qhsf_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayComponentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Earnings'), ('D', 'Deductions'), ('C', 'Configuration')], max_length=1, verbose_name='Type')),
                ('name', models.CharField(max_length=20, verbose_name='Property Name')),
            ],
        ),
    ]
