# Generated by Django 4.1.1 on 2022-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0007_paycomponentproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycomponentproperty',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='Property Code'),
        ),
    ]
