# Generated by Django 4.1.1 on 2022-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0010_alter_area_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycomponent',
            name='category',
            field=models.CharField(choices=[('E', 'Earnings'), ('D', 'Deductions'), ('C', 'Configuration')], default='', max_length=10, verbose_name='category'),
        ),
    ]
