# Generated by Django 4.1.1 on 2022-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0011_alter_paycomponent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycomponent',
            name='properties',
            field=models.JSONField(default={}, verbose_name='Properties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paycomponent',
            name='type',
            field=models.CharField(choices=[('R', 'Rate'), ('A', 'Amount'), ('F', 'Fixed')], default='A', max_length=6, verbose_name='Input Type'),
            preserve_default=False,
        ),
    ]
