# Generated by Django 4.1.1 on 2022-09-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('employee_type', models.CharField(max_length=10, verbose_name='Employee Type')),
                ('payroll_start_date', models.DateField(verbose_name='Payroll Start Date')),
                ('addr1', models.CharField(max_length=120, verbose_name='Address Line 1')),
                ('addr2', models.CharField(max_length=120, verbose_name='Address Line 2')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Zip/Post Code')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('province', models.CharField(max_length=20, verbose_name='Province')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=120, verbose_name='Bank Name')),
                ('bk_currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('account', models.CharField(max_length=20, verbose_name='Bank Account')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
