# Generated by Django 4.1.1 on 2022-09-22 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1), null=True, verbose_name='Birthday'),
        ),
    ]
