# Generated by Django 4.1.1 on 2022-09-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Pay Component Name')),
                ('alias_name', models.CharField(max_length=120, verbose_name='Pay Statement Description')),
                ('input_type', models.CharField(max_length=20, verbose_name='Input Type')),
                ('status', models.BooleanField(verbose_name='Enabled?')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
