# Generated by Django 4.1.1 on 2022-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='addr1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='addr2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, default='13298213344', max_length=20, verbose_name='Telephone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip/Post Code'),
        ),
    ]
